language: python
python:
  - "3.5"

install:
  - "pip install sphinx_rtd_theme"
  - "pip install -e ."
  - "pip install travis-sphinx"

script:
  - "travis-sphinx --source=doc build"

after_success:
  - "travis-sphinx deploy"
  - "ls -la target/doc/build"